### ISSUE TITLE
How to use the G2P model

### ISSUE THREAD

**Issue by changeforan** [tiberiu44/TTS-Cube#12]
Hi, I have trained a G2P model on CMUDICT as Step 0 described. I found 3 files(en-g2p-bestAcc.network  en-g2p.encodings  en-g2p-last.network) in data/model/.
But, how to use them to convert Grapheme to Phoneme? Is it automatically converted in Step 1/2/3?
Thank you.

**Comment by tiberiu44** [comment]
Hi,

I'll do an update to TTS Cube to make it use the g2p in the corpus import step (1). I'll let you know as soon as it's done.
