### ISSUE TITLE
Negative loss when training  step2

### ISSUE THREAD

**Issue by shartoo** [tiberiu44/TTS-Cube#22]
Here is my output of training step2

```
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Found 4995 training files and 5 development files
	Rendering devset
		1/5 processing file data/processed/dev/0000001 
		2/5 processing file data/processed/dev/0000002 
		3/5 processing file data/processed/dev/0000003 
		4/5 processing file data/processed/dev/0000004 
		5/5 processing file data/processed/dev/0000005 

Starting epoch 1
Shuffling training data
	1/4995 processing file data/processed/train/0000007
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  1.29it/s]
 avg loss=0.9230358004570007 execution time=0.8138909339904785
	2/4995 processing file data/processed/train/0000008
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  1.47it/s]
 avg loss=0.8607208132743835 execution time=0.714789867401123
...
avg loss=0.1945137083530426 execution time=0.626471757888794
	17/4995 processing file data/processed/train/0000022
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  1.46it/s]
 avg loss=0.0572626106441021 execution time=0.7513647079467773
	18/4995 processing file data/processed/train/0000023
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  1.68it/s]
 avg loss=-0.061442214995622635 execution time=0.6261122226715088
	19/4995 processing file data/processed/train/0000024
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  1.47it/s]
 avg loss=-0.18586862087249756 execution time=0.7162132263183594
	20/4995 processing file data/processed/train/0000025
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  1.68it/s]
 avg loss=0.06383810192346573 execution time=0.6265075206756592
	21/4995 processing file data/processed/train/0000026
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  1.67it/s]
 avg loss=-0.20782051980495453 execution time=0.628434419631958
	22/4995 processing file data/processed/train/0000027
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  1.46it/s]
 avg loss=-0.31225016713142395 execution time=0.7171187400817871
	23/4995 processing file data/processed/train/0000028
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  1.30it/s]
 avg loss=-0.5820147395133972 execution time=0.8073093891143799
	24/4995 processing file data/processed/train/0000029
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  1.68it/s]
 avg loss=-0.46214190125465393 execution time=0.6245768070220947
	25/4995 processing file data/processed/train/0000030
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  1.46it/s]
 avg loss=-0.7601555585861206 execution time=0.720339298248291
	26/4995 processing file data/processed/train/0000031

```

**Comment by shartoo** [comment]
Training command is 

```
python3 cube/trainer.py --phase=2 --use-gpu --set-mem 8192 --autobatch --batch-size 8000
```

**Comment by tiberiu44** [comment]
Hi @shartoo and thank you for trying this repo.

First of all, the loss is ok. The vocoder is adapted from [ClariNet](https://github.com/ksw0306/ClariNet) - it is also stated in the README.md [here](https://github.com/tiberiu44/TTS-Cube/tree/master/cube/models/clarinet).

The Wavenet Teacher converges at approx -5:
```
avg loss=-5.1320459842681885 execution time=0.9502861499786377
	14330/33378 processing file data/processed/train/tim_rnd1_031
 avg loss=-4.770190715789795 execution time=1.1390399932861328
	14331/33378 processing file data/processed/train/pss_rnd2_372
 avg loss=-5.0867760181427 execution time=1.509335994720459
	14332/33378 processing file data/processed/train/ddm_rnd2_015
 avg loss=-4.78255295753479 execution time=1.4224278926849365
	14333/33378 processing file data/processed/train/pcs_rnd1_112
 avg loss=-4.98662269115448 execution time=2.6414287090301514
	14334/33378 processing file data/processed/train/anca_dcnews_0511
```

and the student at an avg of 1:

```
avg loss=0.7133142787497491 execution time=4.505815505981445
	26163/33378 processing file data/processed/train/fds_rnd1_305
 avg loss=1.775545024871826 execution time=5.89064359664917
	26164/33378 processing file data/processed/train/LJ042-0130
 avg loss=0.6538035869598389 execution time=8.293503761291504
	26165/33378 processing file data/processed/train/anca_dcnews_0661
 avg loss=2.474295496940613 execution time=2.7659800052642822
	26166/33378 processing file data/processed/train/sgs_rnd1_246
 avg loss=1.0989967435598373 execution time=4.755731821060181
	26167/33378 processing file data/processed/train/LJ004-0079
```

It's the first time a saw negative loss also and I thought it was an error, but the model converged just fine. I haven't got the chance to update the README.md on the main repo, but the batch-size of 8000 is really large. Now this value refers to the number of frames, so you multiply with 256 to get samples. I got good results by training the teacher with a batch size of 8 and the student with 5 (larger memory footprint).

I've added examples for the [IAF vocoder](https://github.com/tiberiu44/TTS-Cube/tree/master/examples/vocoder/iaf)

**Comment by shartoo** [comment]
Thank you for your reply ,i 'll keep go on this repo.Batch-size=8000 went OOM on my 1080ti gpu now ,i changed it into 1000 and got OOM again ,i'll try 512 then.

**Comment by shartoo** [comment]
It's strange that OOM only occur when training stage ran into 4500 of 4995.

**Comment by tiberiu44** [comment]
That batch size is still too large. Try 32. On an 12GB 1080TI. I could only get batch size 12 to work. You probably ran into OOM there, because you training files might be small

**Comment by shartoo** [comment]
It takes about  2mins to synthesize a audio  and the the result is broken which cannot be played.Here is the plot image of synthesized audio

**Comment by shartoo** [comment]
![_20190215101951](https://user-images.githubusercontent.com/5716282/52830446-b4d88200-310b-11e9-975c-f0021aadcf0c.png)

**Comment by shartoo** [comment]
![_20190215102350](https://user-images.githubusercontent.com/5716282/52830494-db96b880-310b-11e9-9b62-3047cd067d14.png)

**Comment by shartoo** [comment]
They are all output of stage 2 namely training vocoder this may be normal ,i'll post my result later.

**Comment by tiberiu44** [comment]
Yes. My suggestion is to use only 3-4 files for development (synthesis). Also, good results are obtained after training for weeks. 

It will probably be faster if you use the pre-trained models here: https://github.com/tiberiu44/TTS-Cube/tree/master/examples/vocoder/iaf

Take nn_vocoder.network.bz2 and pnn_vocoder.network.bz2, unzip them and put them in data/models/

**Comment by shartoo** [comment]
Got an error :

```
cuda:0
[Encoding]
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
[dynet] random seed: 9
[dynet] allocating memory: 2048MB
[dynet] memory allocation done.
[Vocoding]
Traceback (most recent call last):
  File "cube/synthesis.py", line 154, in <module>
    synthesize(params.speaker, params.txt_file, params.output_file, params)
  File "cube/synthesis.py", line 98, in synthesize
    pvocoder.load('data/models/pnn_vocoder')
  File "/media/deepblue/5423aeab-3898-4250-9592-790ac3ce4cd4/deepblue/tts/TTS-Cube/cube/models/vocoder.py", line 208, in load
    self.model_s.load_state_dict(torch.load(output_base + ".network", map_location='cuda:0'))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'data/models/pnn_vocoder.network'
```
I checked the file and it did not exists,what's wrong ?

**Comment by shartoo** [comment]
I'm training a Mandarin model,so  i cannot use  your pretrained model to speed up ? The error was caused by step4 synthesizing a speech .

**Comment by tiberiu44** [comment]
To answer your first question, the file is missing, because you did not train the parallel vocoder yet. And second, yes, you can use the pretrained model to speedup construction of your mandarin vocoder. It is not language dependent. Furthermore, it could actually work out-of-the-box (no training needed) because this is a multipleaker vocoder. Just try to unpack both networks into the data/models folder and to a synthesis.

However, you still need to train the encoder, but it is really fast. 

Let me know how if it works for you.

**Comment by tiberiu44** [comment]
You could also test to see how the vocoder works on the gold-standard data. The easiest way is to unpack both networks in the same ```data/models``` and do a short training step for the parallel vocoder:
```
python3 cube/trainer.py --phase=4 --use-gpu --set-mem 8192 --autobatch --batch-size 5 --learning-rate=0.0001
```

After one epoch/or 5000 training files, it will synthesize the development set in ```data/output```

**Comment by shartoo** [comment]
Thank you very much ,it works. But the result is noisy and lost feature of speaker. The attached files in `my_audio.zip` contains:  `generated.wav`  is synthesized file and `sample.wav` is training sample .I just trained 
```
python3 cube/trainer.py --phase=4 --use-gpu --set-mem 8192 --autobatch --batch-size 5 --learning-rate=0.0001
```
and the loss valus is not stable which range from  3.58220624923 to 11.74783563, should i train the model more steps?
[my_audio.zip](https://github.com/tiberiu44/TTS-Cube/files/2879097/my_audio.zip)

**Comment by tiberiu44** [comment]
I see the sample is at 16khz. This model will not work for you, since it is trained on audio, which is downsampled from 48khz to 24khz. You can either get you input data from a higher sample rate source (upsampling will not work) or retrain the both the vocoder and parallel vocoder. 

If your data is only 16khz and if you decide to retrain everything, I suggest you add ```--sample-rate=16000``` in all steps (phase 1, 2 and 4). It doesn't make sense to stress the model to learn generating samples at a higher sample rate than you original audio. You also need to run --phase=1 and reimport the corpus.

**Comment by shartoo** [comment]
It seems a  long term task ,i'll try later but it'll be days later.So the best way is training with 24khz or 48khz samples with your pretrained model .

**Comment by tiberiu44** [comment]
If you go for a high sample rate speech corpus >=24khz, you might not event require any retraining of the vocoders. Just take any audio file (>=24khz) import it into the devset (you could just change the --train-folder location, let it import it into data/processed/train and then just move all the associated files into dev) and try a --phase=4.

To synthesize the data directly, just uncomment line 81 in cube/trainers/vocoder.py. It should look like this:
```# self.synth_devset(batch_size, target_sample_rate)```
just remove the comment and the system will start by synthesizing the development set using the preloaded models.

**Comment by tiberiu44** [comment]
If you want to run this fast test and you don't have any data, I suggest going for [VCTK](https://homepages.inf.ed.ac.uk/jyamagis/page3/page58/page58.html). The data is at 96 or 48Khz. I'm also thinking on training the vocoder using this data, mainly because it has 109 different speakers so it should really increase generalization capacity of the vocoder.

**Comment by tiberiu44** [comment]
I'm closing this issue for now.
