### ISSUE TITLE
Pretrained text encoder for included IAF model

### ISSUE THREAD

**Issue by entn-at** [tiberiu44/TTS-Cube#23]
Hi Tiberiu,

would you be able to share a pretrained text encoder model for the included IAF model? 

Thanks,
Ewald

**Comment by tiberiu44** [comment]
I have a model for Romanian which I will share in a couple of days. I'm also (orking on English, but that is going to come later. I'm experimenting with style transfer at the moment.

What language are you interested in?

**Comment by entn-at** [comment]
Thanks for letting me know! I'm primarily interested in English (just for testing), but I'd like to experiment with other languages as well (for example German, but my current data isn't clean enough to train models that sound pleasant).
