### ISSUE TITLE
Is there any interest in providing a model trained in Brazilian Portuguese?

### ISSUE THREAD

**Issue by Edresson** [tiberiu44/TTS-Cube#27]
Hello, I recently developed a dataset for voice synthesis in Brazilian Portuguese using my own voice, called TTS-Porguese Corpus, the base has approximately 10 hours of talk, is available at: https://github.com/Edresson/TTS-Portuguese-Corpus

I have already successfully trained the DCTTS model in the dataset.

 Is anyone interested in training/adjusting the hyperparameters of the model to get a TTS model in Portuguese?

**Comment by tiberiu44** [comment]
This sounds great. Getting more languages in TTS-Cube is definetely on the roadmap. 

I'm still wrapping up the English model, but I would like to give you corpus a try after that.

**Comment by tiberiu44** [comment]
I'm going to close this issue for now. I'm will work on an English multispeaker vocoder for now.
