### ISSUE TITLE
Demo on Colab, possible improvements? 

### ISSUE THREAD

**Issue by roodrallec** [tiberiu44/TTS-Cube#29]
Hi,

I ran the updated English model in Google Colab, find the code here:
https://colab.research.google.com/drive/1L6BYGA0CmQhF6FULWbVr4-yZeKtp4uPK

The synthesis is good, but improvement could be in the pronunciation of the vowels, which sound as if they are underwater, and the consonants, which are a bit sharp. Any idea why this is, or how this could be solved?

Thank you for creating this project, and making it available :)

**Comment by tiberiu44** [comment]
@roodrallec , your notebook is excellent. I would like to include it as a runtime example for TTS-Cube, if this is ok with you. I'm actually working on a better model which uses g2p and global style tokens for English. I have some [examples here](https://github.com/tiberiu44/TTS-Cube/tree/dev.g2p%2Bstyle/examples/e2e/en/clarinet), but it's still in progress. However, they seem better than the current model.

Also, I'm training a [waveglow](https://github.com/NVIDIA/waveglow) as a vocoder, to see if it provides better e2e results.

**Comment by roodrallec** [comment]
Sure, use it as you please. Waveglow samples sound awesome... Good luck!

**Comment by tiberiu44** [comment]
Hi @roodrallec ,

I've just updated the examples for English and pushed the models. It would be great if you could update your Notebook to use this branch instead. You have to copy the nn and pnn networks from the models file (not just the encoder). Also, for synthesis, you need to specify the g2p model and speaker:

```bash
python3 cube/synthesis.py --target-sample-rate=16000 --g2p-model=data/models/en-g2p --input-file=../test.en.1 --output-file=../en/cat.test.en.1.wav --speaker=cat --use-gpu
```

The list of speakers is:
```
SPEAKER:cat	
SPEAKER:clb	
SPEAKER:lnh	
SPEAKER:eey	
SPEAKER:aew
SPEAKER:fem	
SPEAKER:bdl
SPEAKER:ksp	
SPEAKER:rms	
SPEAKER:axb	
SPEAKER:jmk
SPEAKER:ahw	
SPEAKER:gka	
SPEAKER:ljm
SPEAKER:rxr
SPEAKER:awb	
SPEAKER:lj	
SPEAKER:slp	
SPEAKER:slt
SPEAKER:aup	
```

**Comment by tiberiu44** [comment]
@roodrallec : I actually changed your notebook a little. Thanks again for sharing. I would really like to include this as a tutorial, but I think it would be fair for you to do the pull request. This is my current version of code: [tts-cube-test](https://colab.research.google.com/drive/1cws1INmucRJ702eV4sKNJHzMDvrkg_lh)

**Comment by roodrallec** [comment]
Sure, which folder would you like it in?

**Comment by tiberiu44** [comment]
The examples folder would be great. I think it would be ok to also link this from README.md

Thanks again!

**Comment by roodrallec** [comment]
I think I need push access to the repo, unless there's a magic way to create a PR without permissions from an open issue.

**Comment by tiberiu44** [comment]
I just added you as a collaborator. Normally, you can always create a PR from your fork, if tou are not a collaborator on a repo.

**Comment by roodrallec** [comment]
Awesome, all done, thanks. I was going to use TTS cube as one of the components for my master thesis, but ran out of time unfortunately. Did you create TTS cube as part of a research project?

**Comment by tiberiu44** [comment]
It was just for fun, I guess

**Comment by tiberiu44** [comment]
Do you think this issue can be closed?
