### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by balbertalli** [tiberiu44/TTS-Cube#3]
No idea what the dependencies are for this repo. Apparently it requires python 2 (due to the use of xrange) and is using an old version of scipy ("module scipy.misc has no attribute 'toimage'").  Also, did the folder structure change? Because trainer.py cannot find 'data/processed/train'. I had to manually correct it to '../data/processed/train' (many times because it is hardcoded all over the place). 

You may be on to something, but this repo is unusable by others as it is.

**Comment by tiberiu44** [comment]
Hi @balbertalli,

Thank you for the feedback. I will update the repo next week with requirements.txt, instructions and examples for training and synthesis.

**Comment by tiberiu44** [comment]
I'm working on a docs branch (https://github.com/tiberiu44/TTS-Cube/tree/dev.documentation). Hopefully, I will finish it by the end of the week. Meanwhile, if you could try the installation steps (https://github.com/tiberiu44/TTS-Cube/blob/dev.documentation/GETTING_STARTED.md) of the requirements and DyNet and let me know if everything works for you, it would be great.
