### ISSUE TITLE
how to synthesize from melspectogram directly without using encoder

### ISSUE THREAD

**Issue by saibharani** [tiberiu44/TTS-Cube#32]
can we synthesize directly from melspectrogram without using encoder

**Comment by tiberiu44** [comment]
Hi,

You can use the vocoder here: https://github.com/ksw0306/ClariNet

It has the same format, so you can use my pretained 16khz model.

Best, 
Tibi

**Comment by saibharani** [comment]
while synthesizing using clarinet repo mentioned above using your pretrained model which file should we use synthesize.py or synthesize_student.py and if it is synthesize_student.py what should we give for the argument --teacher-name
thank you

**Comment by tiberiu44** [comment]
synthesize_student
