### ISSUE TITLE
phase 2 saves model at 'data/models/rnn_vocoder' but resumes from 'data/models/rnn'

### ISSUE THREAD

**Issue by Harlan-pku** [tiberiu44/TTS-Cube#4]
Thank you for this awesome work.

When I am trying to resume my training phase 2, an error occurs that 
`RuntimeError: Could not read model from data/models/rnn.network`

I check the code and found that the Trainer store the model at `data/models/rnn_vocoder` ([code here](https://github.com/tiberiu44/TTS-Cube/blob/master/cube/trainers/vocoder.py#L83)) and resumes the model from `data/models/rnn` ([code here](https://github.com/tiberiu44/TTS-Cube/blob/master/cube/trainer.py#L222))

**Comment by tiberiu44** [comment]
Hi @Harlan-pku,

Thank you for noticing this. I'm doing the update right now.
